title:
  ja: "おもしろゲーム神殿"
  en: "Omoshiro Game Sanctuary"

subtitle:
  ja: "アクションゲーム＆シミュレーションRPGをつくろう"
  en: "Create Action Games & Simulation RPGs"

header_text:
  ja: "無料ゲーム＆ゲーム制作ソフトを公開中"
  en: "Free games & game creation tools available"

home_text:
  ja: "おもしろゲーム神殿TOP"
  en: "Home"

url: "https://omoshiro-game.github.io"
baseurl: "" # the subpath of your site, e.g. /blog

excerpt_separator: "<!--more-->"

collections:
  pages:
    output: true
    permalink: /:path/
  pages_en:
    output: true
    permalink: /en/:path/

defaults:
  - scope:
      path: '_pages_en/'
      type: pages_en
    values:
      # permalink: '/en/:path/'
      lang: en
      layout: default
  - scope:
      path: '_pages/'
      type: pages
    values:
      # permalink: '/:path/'
      lang: ja
      layout: default
  


encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
  toc_levels: 2..3

# permalink: /:path/
# layouts_dir: _layouts
# includes_dir: _includes

future: true